# Generated by Django 4.0.4 on 2022-06-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.IntegerField(blank=True, default=0, max_length=9, null=True),
        ),
    ]
