# Generated by Django 4.0.4 on 2022-08-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_tag_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='related_posts',
            field=models.ManyToManyField(to='posts.post'),
        ),
    ]
