# Generated by Django 4.0.4 on 2022-08-10 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_message_id_alter_message_seen'),
        ('posts', '0008_remove_post_tags_tag_related_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='related_posts',
        ),
        migrations.AddField(
            model_name='tag',
            name='related_posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
